name: mpt-7b-lima
image: mosaicml/pytorch:1.13.1_cu117-python3.10-ubuntu20.04 
gpu_num: 8
gpu_type: a100_80gb

scheduling:
    resumable: true # Makes job preemptible.
    priority: medium # Allows higher priority jobs to preempt you

integrations:
- integration_type: git_repo
  git_repo: mosaicml/llm-foundry
  git_branch: main # use your branch
  pip_install: -e .[gpu]
  ssh_clone: false # Should be true if using a private repo
# - integration_type: wandb
#   # The Weights and Biases project name
#   project: 
#   # The username or organization the Weights and Biases project belongs to
#   entity: 

command: |
  cd llm-foundry/scripts
  composer train/train.py /mnt/config/parameters.yaml

# The below is injected as a YAML file: /mnt/config/parameters.yaml
# but is not used in this example.
parameters:
  # trying to IFT a huggingface mpt-7b model
  max_seq_len: 2048
  global_seed: 17
  dist_timeout: 6000000

  # Run Name
  run_name:  # If left blank, will be read from env var $RUN_NAME

  model:
    name: hf_causal_lm
    pretrained: true
    pretrained_model_name_or_path: mosaicml/mpt-7b
    config_overrides:
      learned_pos_emb: false
      attn_config:
        attn_impl: triton
        # "attn_uses_sequence_id": decides if we're going to mask other pairs
        attn_uses_sequence_id: false # <---- RIGHT HERE :)

  # Tokenizer
  tokenizer:
    name: mosaicml/mpt-7b 
    kwargs:
      model_max_length: ${max_seq_len}


  # Dataloaders
  train_loader:
    name: finetuning
    dataset:
      hf_name: aditijha/processed_lima
      split: train
      max_seq_len: ${max_seq_len}
      allow_pad_trimming: false
      decoder_only_format: true
      shuffle: true
    drop_last: true
    num_workers: 8
    pin_memory: false
    prefetch_factor: 2
    persistent_workers: true
    timeout: 0

  icl_seq_len: 2048
  icl_tasks:
  -
    label: boolq
    dataset_uri: eval/local_data/reading_comprehension/boolq.jsonl
    num_fewshot: [10]
    icl_task_type: multiple_choice
    continuation_delimiter: "\nAnswer: "
    max_seq_len: ${icl_seq_len}

  # Optimization
  scheduler:
    name: linear_decay_with_warmup  
    t_warmup: 50ba  
    alpha_f: 0

  optimizer:
    # Based on Dolly
    name: decoupled_adamw
    lr: 5.0e-6
    betas:
    - 0.9
    - 0.99
    eps: 1.0e-8
    weight_decay: 0

  algorithms:
    gradient_clipping:
      clipping_type: norm
      clipping_threshold: 1.0

  max_duration: 10ep
  # not running ICL evals during finetuning
  eval_interval: 10ep
  # eval_subset_num_batches: -1
  # eval_first: true
  global_train_batch_size: 48  # somewhere in the 6-8 * numgpus range seems good

  # System
  seed: ${global_seed}
  device_eval_batch_size: 4
  device_train_microbatch_size: 4
  precision: amp_bf16

  # FSDP
  fsdp_config:
    sharding_strategy: FULL_SHARD
    mixed_precision: PURE
    activation_checkpointing: true
    activation_checkpointing_reentrant: false
    activation_cpu_offload: false
    limit_all_gathers: true
    verbose: false

  # Logging
  progress_bar: false
  log_to_console: true
  console_log_interval: 1ba

  callbacks:
    speed_monitor:
      window_size: 10
    lr_monitor: {}
    memory_monitor: {}
    runtime_estimator: {}
    generate_callback:
      batch_log_interval: 20
      do_sample: true
      max_new_tokens: 100
      prompts:
      - What is the language R used for?
      - Give me an itinerary for a weekend trip to New York.
      - Tell me about the history of the United States.
      temperature: 1
      top_k: 50
      top_p: 0.95
      use_cache: true
  
  # loggers:
  #   wandb:
  #     project: 
  #     entity: 

  # Checkpoint to local filesystem or remote object store
  save_interval: 2ep
  save_folder: ... # path to save checkpoints to
